import { motion } from "framer-motion";
import { Database, Server, Globe, Shield, Boxes, GitBranch } from "lucide-react";

interface ArchitecturePanelProps {
  activeAgent: string;
}

const architectureNodes = [
  { id: "frontend", label: "Frontend Layer", icon: Globe, x: 50, y: 30 },
  { id: "api", label: "API Gateway", icon: Server, x: 50, y: 50 },
  { id: "services", label: "Microservices", icon: Boxes, x: 25, y: 70 },
  { id: "database", label: "Database", icon: Database, x: 75, y: 70 },
  { id: "auth", label: "Auth Service", icon: Shield, x: 50, y: 90 },
];

const connections = [
  { from: "frontend", to: "api" },
  { from: "api", to: "services" },
  { from: "api", to: "database" },
  { from: "services", to: "auth" },
  { from: "database", to: "auth" },
];

const ArchitecturePanel = ({ activeAgent }: ArchitecturePanelProps) => {
  return (
    <div className="h-full glass-card-hover p-6 overflow-auto custom-scrollbar">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-semibold text-foreground">Project Architecture</h3>
          <p className="text-sm text-muted-foreground mt-0.5">
            System topology generated by {activeAgent.charAt(0).toUpperCase() + activeAgent.slice(1)} Agent
          </p>
        </div>
        
        <div className="flex items-center gap-2">
          <GitBranch className="w-4 h-4 text-primary" />
          <span className="text-xs font-medium text-muted-foreground">main</span>
        </div>
      </div>
      
      {/* Architecture Diagram */}
      <div className="relative h-80 rounded-xl bg-obsidian/50 border border-primary/10 overflow-hidden">
        {/* Grid Background */}
        <div 
          className="absolute inset-0 opacity-10"
          style={{
            backgroundImage: `
              linear-gradient(hsl(183 100% 50% / 0.1) 1px, transparent 1px),
              linear-gradient(90deg, hsl(183 100% 50% / 0.1) 1px, transparent 1px)
            `,
            backgroundSize: "30px 30px",
          }}
        />
        
        {/* Connection Lines */}
        <svg className="absolute inset-0 w-full h-full pointer-events-none">
          <defs>
            <linearGradient id="connectionGradient" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor="hsl(183, 100%, 50%)" stopOpacity="0.4" />
              <stop offset="100%" stopColor="hsl(275, 100%, 50%)" stopOpacity="0.4" />
            </linearGradient>
          </defs>
          
          {connections.map((conn, index) => {
            const fromNode = architectureNodes.find(n => n.id === conn.from);
            const toNode = architectureNodes.find(n => n.id === conn.to);
            if (!fromNode || !toNode) return null;
            
            return (
              <motion.line
                key={index}
                x1={`${fromNode.x}%`}
                y1={`${fromNode.y}%`}
                x2={`${toNode.x}%`}
                y2={`${toNode.y}%`}
                stroke="url(#connectionGradient)"
                strokeWidth="2"
                strokeDasharray="5,5"
                initial={{ pathLength: 0, opacity: 0 }}
                animate={{ pathLength: 1, opacity: 1 }}
                transition={{ duration: 1, delay: index * 0.1 }}
              />
            );
          })}
        </svg>
        
        {/* Architecture Nodes */}
        {architectureNodes.map((node, index) => (
          <motion.div
            key={node.id}
            className="absolute transform -translate-x-1/2 -translate-y-1/2"
            style={{ left: `${node.x}%`, top: `${node.y}%` }}
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2 + index * 0.1, type: "spring" }}
          >
            <div className="glass-card-hover p-3 rounded-lg flex items-center gap-2 cursor-pointer group">
              <div className="w-8 h-8 rounded-md bg-gradient-to-br from-primary/20 to-secondary/20 flex items-center justify-center border border-primary/20 group-hover:border-primary/40 transition-colors">
                <node.icon className="w-4 h-4 text-primary" />
              </div>
              <span className="text-xs font-medium text-foreground whitespace-nowrap">
                {node.label}
              </span>
            </div>
          </motion.div>
        ))}
      </div>
      
      {/* Stats */}
      <div className="grid grid-cols-3 gap-4 mt-6">
        {[
          { label: "Components", value: "24" },
          { label: "Endpoints", value: "18" },
          { label: "Dependencies", value: "12" },
        ].map((stat, index) => (
          <motion.div
            key={stat.label}
            className="glass-card p-4 rounded-lg text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 + index * 0.1 }}
          >
            <p className="text-2xl font-bold gradient-text-cyan">{stat.value}</p>
            <p className="text-xs text-muted-foreground mt-1">{stat.label}</p>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

export default ArchitecturePanel;
